---
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  security_group_ids:
    - ci-testing
  instance_type: c3.large
  interface: public
  tags:
    Env: public
    Type: test
    created-by: test-kitchen
    Operator: <%= ENV['USER'] %>

transport:
  name: sftp
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver:
      Name: exhibitor-ubuntu-1404
  - name: ubuntu-16.04
    driver:
      Name: exhibitor-ubuntu-1604
  - name: centos-6
    driver:
      Name: exhibitor-centos-6

suites:
  - name: default
    run_list:
      - recipe[exhibitor::default]
      - recipe[exhibitor::service]

  - name: upstart
    run_list:
      - recipe[exhibitor::default]
      - recipe[exhibitor::service]
    attributes:
      exhibitor:
        service_style: upstart
    excludes:
      - centos-6

  - name: maven
    run_list:
      - recipe[exhibitor::default]
      - recipe[exhibitor::service]
    attributes:
      exhibitor:
        install_method: maven
