---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: centos-6.8

suites:
  - name: default
    run_list:
      - recipe[exhibitor::default]
      - recipe[exhibitor::service]

  - name: upstart
    run_list:
      - recipe[exhibitor::default]
      - recipe[exhibitor::service]
    attributes:
      exhibitor:
        service_style: upstart
    includes:
      - ubuntu-14.04

  - name: maven
    run_list:
      - recipe[exhibitor::default]
      - recipe[exhibitor::service]
    attributes:
      exhibitor:
        install_method: maven
